### ISSUE TITLE
built-in string function like ToLower() raise an exception

### ISSUE THREAD

**Issue by moh-hassan** [gearz-lab/lambda2js#15]
The following test case raise an exception:

        [TestMethod]
        public void Test2()
        {
            Expression<Func<MyClass, string>> expr = x => x.Name.ToLower();
            var js = expr.CompileToJavascript(new JavascriptCompilationOptions(JsCompilationFlags.ScopeParameter));          
            Assert.AreEqual("function(Name){return Name.toLowerCase();}", js);     
        }

Exception error:

          Test method Lambda2Js.Tests.GeneralTests.Test1 threw exception: 
           System.NotSupportedException: By default, Lambda2Js cannot convert custom instance methods, only static ones. `ToLower` is not static.
...

Can lambda2js support the built-in functions that have a corresponding one in js?
e.g the string method  ToLower()  ===> can be mapped to js  toLowerCase()

**Comment by yasmoradi** [comment]
See https://github.com/gearz-lab/lambda2js/pull/16

**Comment by masbicudo** [comment]
This issue is now solved. Thanks @ysmoradi for the PR.

**Comment by moh-hassan** [comment]
Thanks for resolving issue.
I test the release 3.0.1 and it's working fine for both toLowerCase and toUpperCase.

**Comment by moh-hassan** [comment]
Issue is resolved and can be closed.
Thanks
