### ISSUE TITLE
Sign DLLs

### ISSUE THREAD

**Issue by ppekrol** [gearz-lab/lambda2js#18]
Is there a possibility for the DLLs to be signed? I'm getting following error:

```
CS8002: Referenced assembly 'Lambda2Js, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

Using '3.0.1' NuGet package. The '1.0.0.0' also means that the File version is not set.

**Comment by masbicudo** [comment]
Sure!

I'll compile a signed version of the package and upload it to nuget.

Thanks for asking... it's always nice to see that this project is useful for someone.

**Comment by ppekrol** [comment]
Awesome! Thanks!

**Comment by masbicudo** [comment]
I have uploaded a signed package to nuget.
https://www.nuget.org/packages/Lambda2Js.Signed/3.0.1
