### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by masbicudo** [gearz-lab/lambda2js#2]
Create a NuGet package and submit it to nuget.org

**Comment by andrerpena** [comment]
Is it finished?

**Comment by masbicudo** [comment]
Yes... and no... I have submitted it to my account in nuget.org... but I have to create a `gearz-lab` account in nuget.org, for coherence.

**Comment by masbicudo** [comment]
The account does not matter... the URL does not change if I transfer it latter.
