### ISSUE TITLE
Literal null on string type raises an exception

### ISSUE THREAD

**Issue by bgurmendi** [gearz-lab/lambda2js#27]
This new test throws a null pointer exception.

``
        [TestMethod]
        public void NullLiteralToString()
        {
            Expression<Func<string>> expr = () => null;
            var js = expr.Body.CompileToJavascript();
            Assert.AreEqual("null", js);
        }
``

**Comment by bgurmendi** [comment]
On this pull request is the solution: #28

**Comment by bgurmendi** [comment]
@masbicudo thanks for the fast publish to Nuget.

I'm testing 3.1.3 version on our enviroment and the bug still appears. I have clean all dll and restored the packages but still.

¿Could be and error on the packaging procedure?

**Comment by masbicudo** [comment]
Hi, I made some changes to allow testing the deployed NuGet packages in the project.
All tests are passing.

These are the new test projects (they are generated by the project generator)

For signed NuGet packages:
- Lambda2Js.NuGet.Signed.Tests.netcoreapp1.1.csproj
- Lambda2Js.NuGet.Signed.Tests.netcoreapp2.0.csproj

For unsigned NuGet packages:
- Lambda2Js.NuGet.Tests.netcoreapp1.1.csproj
- Lambda2Js.NuGet.Tests.netcoreapp2.0.csproj

Specifically, the `NullLiteralToString` test is passing too.

I really don't know what could be wrong...
Can you share the piece of your code that is raising the exception?
