### ISSUE TITLE
Cannot use UsedImplicitly attribute with the "WithInheritors" flag due to assembly versioning bug.

### ISSUE THREAD

**Issue by Mike-Logit** [gearz-lab/lambda2js#33]
Hi, I am using the `JetBrains.Annotations` NuGet package and have experienced a compatibility issue with your `Lambda2js` NuGet package (which the jetbrains package uses as a dependency). 

I reported the problem here: https://github.com/JetBrains/JetBrains.Annotations/issues/4

> Hi, I hope this is the right place to report a bug. I cannot use [UsedImplicitly(ImplicitUseTargetFlags.WithInheritors)] in my codebase because there is a dependency issue with JetBrains.Annotations. It says:
> 
> The type 'ImplicitUseTargetFlags' exists in both 'JetBrains.Annotations, Version=2021.2.0.0, ...' and 'Lambda2Js.Signed, Version=3.1.3.0, ...',
> 
> but JetBrains.Annotations has a dependency on .NetStandard v1.0, and .NetStandard v1.0 has a dependency on that Lambda2Js.Signed package, so I cannot fix the dependency problem myself.
> 
> I want to use these flags (e.g., ImplicitUseTargetFlags) but can only use the UsedImplicitly attribute without flags. I hope this can get fixed as inheritance would be a great feature to use with these attributes. This would let me have a base class with the UsedImplicitly attribute and then all my derived classes would not need to also have this attribute and it can be assumed that if I'm deriving from the base class then it will be used implicitly (which is great for many design patterns). Thank you.

But they closed it and said I might want to open up an issue with your library instead.

**Comment by masbicudo** [comment]
Hey, thanks for reporting this problem.
I'll take a look at this and merge the PR.

**Comment by masbicudo** [comment]
I have merged and published a new NuGet package.
Could you please try the new NuGet package and tell me the problem persists?

**Comment by Mike-Logit** [comment]
@masbicudo yes that solved the issue, thank you! Keep up the great work 👍 

I've suggested to the `JetBrains.Annotations` team that they should update their dependency of `Lambdajs.Signed` to the latest version as well.
