### ISSUE TITLE
Nuget package doesn't work with .NET 4.0 project

### ISSUE THREAD

**Issue by bryantlikes** [gearz-lab/lambda2js#8]
The current nuget package doesn't work with .NET 4.0 project and it seems it is because the lib has a folder for: portable-net40**3**%2Bsl50%2Bwin%2Bwpa81%2Bwp80. 

When I change it to: portable-net40%2Bsl50%2Bwin%2Bwpa81%2Bwp80 (I removed the 3 in net403) 

Then it works.

**Comment by masbicudo** [comment]
Sorry for not answering before. The project was targeting .Net4.0.3 in the portable profile. This was not intentional. I changed the target .Net profile to v4.0. Can you confirm whether it's working now?

**Comment by masbicudo** [comment]
I have created a new .Net 4.0 project and used the newly uploaded package... it seems to be working now. If you have any problems, please, reopen the issue.
